// <auto-generated />
namespace Domains.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class updateuserinfo11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateuserinfo11));
        
        string IMigrationMetadata.Id
        {
            get { return "202503281213447_update-userinfo11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
